---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-secure-tls
  namespace: mosquitto
spec:
  preferredChain: "ISRG Root X1"
  secretName: mosquitto-secure-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - "mqtt-secure.${SECRET_DOMAIN}"
