---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eclipse-mosquitto
      pullPolicy: IfNotPresent
      versio : "2.0.18"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /mosquitto/data
        size: "1Gi"
      configinc:
        enabled: true
        storageClass: "nfs-client"
        mountPath: /mosquitto/configinc
        accessMode: ReadWriteOnce
        size: 100Mi
    resources:
      requests:
        memory: 20Mi
        cpu: 100m
      limits:
        memory: 50Mi
        cpu: 200m
