---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eclipse-mosquitto
      pullPolicy: IfNotPresent
    service:
      main:
        type: LoadBalancer
        spec:
          loadBalancerIP: "192.168.1.21"
          externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /mosquitto/data
        size: "1Gi"
      configinc:
        enabled: true
        storageClass: "nfs-client"
        mountPath: /mosquitto/configinc
        accessMode: ReadWriteOnce
        size: 100Mi
    resources:
      requests:
        memory: 100Mi
        cpu: 250m
      limits:
        memory: 250Mi
        cpu: 500m
