apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - configmap-secure.yaml
  - certificate.yaml
  - secret.sops.yaml
  - helm-release-secure.yaml
  