apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secure-secrets
    namespace: mosquitto
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:7CPzY0dCxELxPBDqQg==,iv:k0T5XWO3KdIFnF/wysVij0suKo2eXbrijV9vdrp8nmg=,tag:hhN7NnlZV34lmpmkSAXeRg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:rXvGg2wsBLB1zJ3/Frsp1r9sOSzfzqHcbhbkLS6IkK/KSoJEIOmcM8XlgZyL2w==,iv:brEWEiNJj7e99mXV1baLkNnnNbHqqA3RXFSIp5DsIG4=,tag:hwvTxqVoQxr5+hpyQfJKVQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T13:49:00Z"
    mac: ENC[AES256_GCM,data:yWOH88h0qcJQmU+uu8IcwIMVWuNQbeEssaSu9aZGwmrZLoDUv1NkjA2Wkwpyt04WgkS+niDN5AvuRG4K47vsOQuMtzpNwRbMxo/PsGEAFtmaDTTGNE2ZQETqBxEL5d81QPjaHB76yjW5SVShjLWUBP3V11yrbnJqq1cd0f95PRA=,iv:7lA14vDqJBwRr0vNCKdTqNy4eisabf8IrpPk2e/LGIM=,tag:IqikDbupBiSQ0cbz+wLThg==,type:str]
    pgp:
        - created_at: "2026-06-27T13:49:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ/9HH1GLE7G4F9pTc6WFOlD4/Cg7CnLM62g8tdYof/EfB7c
            TXx+I2xdbZaUzAJQ4TkZN07H7AAV5APy5Zl7BFfVgRbKbT/JrrsDOpNSbxiYHCK2
            e30XZtQLTBuRNcMZOcsPTaRdKqw71hgC73jTos9gJjS6o7pQMDwFxjuwwbzjWa2f
            CJMxOxOfjlQRjyU7rwijH3j/sMNela4iKOjjpMPHRLJdosI6/mW6Fmxq7NC/KRVc
            dLLODVch+BYlBcQGhFD9vvmVAqL/6qS3VEAZuMx9lnZBclh73UYeZ1BPbBiWLtev
            agMGStAjy9EEWDNqavq8HpOD3n6ScnJik1Tsu7d+qOZAND8O3exq4fI64093ecb0
            NR5S1b7XVF9gzUlnWskfL1To5Qk9QVXLiA0PNvNiuepZlrccvczlHno9YtfiYQBX
            Vz+6RWcIYUIbEgMj3aFtVogpeuWZkBJ+ooUKS0IPB7wNSD9EpyOlpxkat+H7CX8e
            RmuGn9h3XyBmLvIT7lhpE12ZMKLXnxK+mNuFSrHdf4RHpIDFm6pFUXTabpkBxOaR
            d2hN0Qivlzg3z6woFXRYXwJGZB0Q3X6KQJR6tUDCFZFJ5UuJXe32juomSElIm40k
            uHTf/Ezk0bOJJo+TRc31OfMhU1Cq1Es/0TccY22zdsxa49LXs4yddrUJ+ZHrBXPU
            aAEJAhBCOOcJWG0+pGk5dwa0QjVdAH0KxhBXDoszD26UbrcwODTUXvMt18mJ4AbH
            8Sk/FRgPMB8gzmw+Ik10/dxKsWbWUeQNcInZBrymyCenrsdGky9ZIoZUUfjTluNe
            +t/RtubEYixa
            =YM+7
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-06-27T13:49:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAA1HxAKwbLp1fHFY5eOj6d78Maydu0x+//hV3MF+Ao8H2C
            k2u2gZhN22H+pbSbSb7sNqrtpIo7Yv40j8pMPYKApqz1YuNAAwYgeZV1z/2xDj+E
            RdKw3AJ8Bbf6Kn4TFUp/VKBBcbXhwXmdCKynTHFNOjhRzHyew9K2irpiiTgEIUkb
            oeaZS0v54v9voxY5s/CjlarGlJ3WQxFun59SYuhK8xcdK7AABJfuFaOiFkalMhq3
            gLVGML512tEzw0D1ef61FQ6HltoOuriIubSHEXLGuuYq040umBXTuQeqpTEy1VbP
            swAJx0v6/CuAAIngSV0EA/+H/3kAkBhD3cc+FyDUKHSMmhL+G4GFPyQ2KYSyqtZJ
            bVvqVrTxvda6OuB1jl0RjYKCwnz5ufXVe1oXGGfwFqEcMvDWPVf433dxq4ld/ugw
            Zs1kiQboNpRANSO9zPm1DK96jixbU5V5ja2iYbxsSjKra6Rp2h6pC2DTBTxK1u8J
            grg6SRYMoRCOriFgcLgol4SiD9PkJYhi+YB7a9eJ8UCyHleYqdA4ndLE7CRqA1pj
            MT/rjct8HTSRSGij4BjTybLGUOugYl8XhUVnZrF1D0v5u6qDRDsePufSg/AGkUk3
            h7uLYA/aWnQPXA+1pS40XL7N2Emiyw41lRx55cTjilavMEfMfFRV/kNNZws+Vv/U
            aAEJAhDOYFfd6RBjZtz/4CCIdfW2NhVBz007fwiIPMwzqS8LRUivdJyiVeUGZo8t
            wFkdp8H6dX4FrqxGRH/KK6Or6nxbVTP7NlhqefmZHGmWOojJY/JIIxnc7qZ8syHM
            4MRlcjJ4Zlfz
            =3fp+
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    version: 3.13.1
