---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: "1.37.0"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 200Mi
                cpu: 150m
              limits:
                memory: 250Mi
                cpu: 200m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 8*60=480 seconds to start up before it fails
                  periodSeconds: 8
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 9696
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"
            secretName: prowlarr-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
