apiVersion: apps/v1
kind: Deployment
metadata:
  name: tydom2mqtt-deployment
  namespace: tydom2mqtt
  labels:
    app: tydom2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tydom2mqtt
  template:
    metadata:
      labels:
        app: tydom2mqtt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      containers:
      - name: server
        image: fmartinou/tydom2mqtt:3.3.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: TYDOM_MAC
          value: ${SECRET_TYDOM_MAC}
        - name: TYDOM_PASSWORD
          value: ${SECRET_TYDOM_PASSWORD}
        - name: TYDOM_ALARM_PIN
          value: ${SECRET_TYDOM_ALARM_PIN}
        - name: TYDOM_IP
          value: "192.168.1.248"
        - name: MQTT_HOST
          value: ${SVC_MOSQUITTO_ADDR}
        - name: MQTT_PORT
          value: "1883"
