apiVersion: apps/v1
kind: Deployment
metadata:
  name: tydom2mqtt-deployment
  namespace: tydom2mqtt
  labels:
    app: tydom2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tydom2mqtt
  template:
    metadata:
      labels:
        app: tydom2mqtt
    spec:
      containers:
      - name: server
        image: fmartinou/tydom2mqtt:3.3.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                  - "true"
        env:
        - name: TYDOM_MAC
          valueFrom:
            secretKeyRef:
              name: tydom
              key: mac
        - name: TYDOM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tydom
              key: password
        - name: TYDOM_IP
          valueFrom:
            secretKeyRef:
              name: tydom
              key: ip
        - name: MQTT_HOST
          valueFrom:
            secretKeyRef:
              name: mqtt
              key: host
        - name: MQTT_PORT
          valueFrom:
            secretKeyRef:
              name: mqtt
              key: port
        