---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teslamate
  namespace: teslamate
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: teslamate/teslamate
              tag: "2.1.1"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              DATABASE_HOST: 192.168.1.10
              DATABASE_PORT: 5440
              DATABASE_USER: teslamate
              DATABASE_PASS: ${SECRET_TESLAMATE_DB_PASSWORD}
              DATABASE_NAME: teslamate
              MQTT_HOST: ${SVC_MOSQUITTO_ADDR}
              ENCRYPTION_KEY: ${SECRET_TESLAMATE_ENCRYPTION_KEY}
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 500Mi
                cpu: 1000m
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 4000
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-forwardauth-authelia@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "teslamate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "teslamate.${SECRET_DOMAIN}"
            secretName: teslamate-tls-secret
