apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: networking
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:VSFujIMfOYvKHGgC1CXRfObasg9OJJ2nGK3BR5bzLSVHmuC52qyYcofNbQX+MkzLJlRnCueI9Syrsv+V7GZucpapJD084HKZsN6of7Kosoz1ImWN2DAgVCFn42gX+Cqc/KPBOB4u2IaCMx9YdMFZV/PIqBjkakAJLCk+5JiuHv0=,iv:qm8fPCPA6msjBkG+iqVtRjus4Ug2/ztzhGR4ikZ4k7Q=,tag:V9qztilOd8I1mba7aHxfog==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:fSRGm2u0rra0cZZxTPRFAd2U3FIhfNtjqGmBog7xqcY6VLrWYCEPNWqObkwtwyVMdjb8T9ex3xVaKn+LhQc18bCF/AaCHRd36YzJwOfb7ErhdW8JGBua3I823rDa1TDCMkB4jniLf8zq81aNCdKfafMtLA1Ku+peIzmzylgIO2o=,iv:pJD5Kfzsqz5WN4VO8z2KwE0Z+0U9GLhXvy7XzlhmcaQ=,tag:y4Pmp3LhFu+lfksLbMk/SA==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:y4iCayHQPVZUn4nFu4MXMrF+iwP6mIwYmOSLGVS/e3jrBkT3zhqCJSrcaGsaJEZKl74FKtfvdpkMZwRc1jUJcb7AspapNFE9Emncch3+nZCef2afsTq/+gPIgUHXM8Omt9hA7SBK8j/AoDWztElxn2/CGZE0o8auYBPEDgoNWi8=,iv:sZSAIhHP9o0tpaUxv3IzWonc8c3K/5Xwjo3P5zVsGXg=,tag:q/W+4hVtL9qcF1wx6e13uQ==,type:str]
    users_database.yml: ENC[AES256_GCM,data:/eF2LX4oIjLK4g4/Z4ZMva1UsMjgFn24dNOwHaa8jZx9JKmxmui+fv2tQ80s94irrxtVUc8mLMFo0XCqOfxKkXvQkQQvO8MyBPEHCayyamy7fLAD0QHt7kJ+4tkKrbpUM7xzCeBKVyyfhmxvu5A1U69MEUlEW1zmgO3bAdGGEzQOzr66izrnDeku7EQCQDRZbnq1lGS+bIFIZV2t6TNLoyOwVDI7ibkuBhtUbEJBPeUW3FBDFCrT/Y+5MutK1vjtY4katkZudG8p+KIRIQll5TeDEKoO9cBNxaLr6CzOJvf+wGHe0Fh0Q46nilGZmHQcrK857tA2FvdjFNE7wBn6l72DhbMJmJc0Ka1GW8Z9txbrLBQ6kHWa8nQnSsW6FkU573t0zFs2ClS+AniainfSVZmFmMWV1iGt+W8OgCgRcvTW6oVtWcQoglt+R14Tl/Z2A+aozMWDvntpA+p1sEmajI7ATn8+5p06lJd5RosNPTOiOHfJQoKjfzl8TbqWLC9rv6LSbPp7joy82boYtQlQN8bFJav6rCUujXSuzbxWfq+UgipI+EC95E67E3PLw6AOWQZpONadiv4PjY5M1EJ64FfWd6MuFT+xtpu+RMa4M7tHBXhvb9xtBHcOtSKYzlXmo5U6UbEYZ7XExn9CPB5TA4jNg/GXEKYLtcPs4Tb/Cu2yS5PUzgoqQ8AdY+1eu40DCID93UJXNgvql+ET,iv:KwbDnonQWtfIuYnWAnbN47yglmb32A7BsXe4ZkLM2yI=,tag:9xGh0Qco9T3RTvkFqFnHIw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T16:47:45Z"
    mac: ENC[AES256_GCM,data:pnqwMbN5Kg58YNUxNzunzRIS3TsHIYEASv6IdDMdHrLEX6eh1wF23kiQWtItpsTRobcGoHO4gyI655WjmJV2kBWHKv7QJSFllRtd4ZWM+GilSAWZSyGJaOdDKfQEbVk++UaiWejJyLqqd7NYCtGbVWGAZzyX9fxJ8a/6MKJwMKI=,iv:yERZw+8grz07VOS9jnVyxlskzaVCq+yDC5OF8ecs0f4=,tag:Y0xbI1mXSy5KPbSAJccPeQ==,type:str]
    pgp:
        - created_at: "2026-09-30T16:47:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ//eJ4pRu+UXDFXTa9Mka/sJ6E8jbiuWuWgpEtRyua48qOm
            3OeYkyJ9kBbGv8FA2I8O5AcIMUWlQqOTcsm9wNQBZvfFu8Sr1/eusWUXiVefUH+R
            K3WFKgZ2JgZjeTuga+q3Kgn5TGO+xeLxrCj9AtlGCKKrMuyIGYAXNP5BiPBFCmkL
            00ybkIjt0Y+8VgD4w3Xtrqgp8Wf1DFZW0G/3Td9z6pJBQG+TdlldYbPTAvczOAi2
            FWjskB6Fpl4uaJlXcuSHmFGb8Qyeg6REEBhXIEXc6jxeWkbMQAWf2rRS50XyDwoa
            xTWxhUVL4Ei2Ruge72UA9uzb68KnU0X0g9c7EkgtRpYkO78Q0HBWQ4ovZkg0Ll/u
            k7L9br6Q+rqj/iuPz/mP7FCooUB1YX2zE/nkuH0N3+Q2VdQKx6GJXEamKmhq5Awy
            ZBD8O3x9qamKuVnuhdGrFzGdgn5fBEyrppipXarD9TaYfI4tK8bG24+9iEpAkJzi
            2U8+Kl6Rajzu0d6va+soWGruEkQ29drsoAXu5kMEZTQ309V4PC52EqnVXkJsPjyj
            MBeoNDx1gVDaDKzNTwYikC2WcZID3woZqM+L2oMHJi9Bkk3QWZG4y64Aetrm8oK6
            qnlU+2fUDxXuOB19ZJ5T19IZjR0IItVaE2dxyyA8VXKF1MUoS3Bz5tWddj7YcQLU
            aAEJAhBA5RM3dIhm5I6d/pGkOyqmwGEFnkqL5aRCPPePCfTakDSNgHS0pSaBrDkE
            1/VBzW8BocWqYCL/NDJe125QNsXpZRcnZUFgc1w2NVQbaO8fl9s3BCbmWILQ7hFj
            PKoitQE4Bwnz
            =d8VX
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-09-30T16:47:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2AQ/5Acf6HjVQBOdKfQGWLI5vpHf/07Ubx71s6cvtQwf3mCSJ
            wmH2MJtLiT/1HKXQIRziyqoK+wBgvPFrqfKLIx4hAjsxfELEEUcQCmZBm0ZQs/0G
            zPyuf4qDMfEoG0xitIvr3GeRBAK72ZfoCVm6MZObDdvYG1nLoQmD6dnsPlbtb0CF
            dSXgmVJoEtOlI7yfH7Br4iseClAvbsuKtUeErrgA/Xk89Tw0a5qsEWe2RvaXvvZ2
            Y5QXUDVsIWOB8tUqWX0jMwPe42ZFAF5roHfmLzBikdEhnTGMjuz2Ij5k6gsGdfUV
            fMrIrV6k8J5Kj7IskDA4u3iTSB2o187PP5zdo1rKdedopIYtQcMzPnpua+/fAjf8
            UBkv03+CeA3fQdORYSLufNXHGqp2tso+MVENEw3s8ZJvYu3HAzI9nM2mx5w2fsCd
            v/rJBSb7JnW3qlTEhPzeEFbcYkGpRGwegrFjZ9viywtdQflktJGmqHTdwDl3Ptbp
            F2PuQc4z43SQJfDofWDrXo6uxfIY6FGOBCyDRtosIUFpD7hrL6Qhckrt8BqG82S+
            70XGHGp+WY8DCGM+Rs/n0QqdulugQiscg1vX/qT7BFQDe+PSSAqVP10C/21TOS9+
            yKBG2+u/KXWiCHdbT5dNOTYhXGfZdcW6Hy9IkMo6UMkQ7u5q0BwRJN5vOToKSvzU
            aAEJAhCCjoxXl19L5/wgx+N8/ywKJsEOXdBOzVS9A0d89TCe90ZwU3KbyfbFUegz
            IURgUdAZAnceDbY3YyLuHAnG+Uo5YrpW9863nr4g3qYGZEz0OsfVGncdEeTMGazl
            TJgzOy59N5XU
            =ZjOY
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    version: 3.13.1
