---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    tunnel: c05a109a-27dc-4815-9e91-a72da43073b9
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: "slskd.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "uptime-kuma.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "sonarr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "radarr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "lidarr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "prowlarr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "minio.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "tesla-fleet.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "music-assistant.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "obsidian-couchdb.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "jellyfin.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "home-assistant.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "navidrome.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "memos.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "jellyseerr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "scrypted.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "bitwarden.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "backrest.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "esphome.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "go2rtc.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "heimdall.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "joal.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "kitchenvault.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "maintainerr.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "node-red.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "shopping-cards.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "transmission.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "yubal.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "zigbee2mqtt.${SECRET_APEX_DOMAIN}"
        originRequest:
          matchSNItoHost: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "auth.${SECRET_APEX_DOMAIN}"
        originRequest:
          noTLSVerify: true
        service: https://traefik.networking.svc.cluster.local:443
      - hostname: "*.${SECRET_DOMAIN}"
        originRequest:
          noTLSVerify: true
        service: https://traefik.networking.svc.cluster.local:443
      - service: http_status:404
