apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
stringData:
    credentials.json: ENC[AES256_GCM,data:7ks6QM0dW5tdjrybTEsYplWB8xM6oL+fpb0jKXKGxqa16TBlLZRLjXMlEnlgfzUbHw1cpmj+XFZ632NG9mTZEAon+IPJwA32+BlL+J/7qIquWbV7NcwkwhC52cmqkkwEpiq6ueJOfM2acKwAiDvGUzqcuezVfNcTgcBFpv6hWv4tIew9motgTzyyHKyLdAoqkwHFC53+wlRVou4SDRMX0y/VRzo0wsW82Ir27rgxzxY=,iv:RoiC2e0fYbknyfqGbojt4I5nz0jj3OWIFVPGWzwuIBg=,tag:uPGJUwKFsTfF3ryehHqiyA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T14:08:14Z"
    mac: ENC[AES256_GCM,data:suoebE83+pFQuEkDk3mMuAhLoT1hx/Nk9LjWgI2748ub5GG4JI3HAwyWE9N/koHtDi6To5Adwb0hx5LTxC+eeijCK65pbCxhuHHAhpuLQDZRQI15MAJ8+Zz3K90afpdYt3xd1UQbxWHc3F7e1+tvmt17EoDnnLLiamh+3EXjEI0=,iv:wYRySUe+b1MkTtV58xBWfSWWZ1HsRv7G/kMEHkm3EHY=,tag:NWGs22c9cX7lqV07DMd62w==,type:str]
    pgp:
        - created_at: "2026-09-19T14:08:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ/9G0wvD3/ivJmYlZFP3OReZ/ycNzSsV2NYZDyvCPDZQva3
            eW+NjC7drhYD5C/GzrWtqiQhuKIqeFp3QUnZ/aTQXVWEqP28jpfgS8mYS7JX52qB
            D5bhzlh07clj3eXyhLqsSuGgpEMCLX6AQVBgtoaCr8BspzkRG+gsJT7q9mK96Kf8
            ShX2jy7Q2GTZsrEWxve4pnOiqX6/BPXPO5aa9iF6uYU4MHZXsD4sYva8xsRSE150
            y+VrdukdSD9JLxAOd3dbkmzgNivI9pAicDvhxhwR9WW2ls5aeJ8mxY5dnslWnopD
            jEqqHkscsGqD9kf8YIu3X+eI+7d31GOIb2r67HRNgPIkwd4O1iSWni6VivxHwVDP
            BSkKo5MBYXwQxRdDCLn2OmRt4uSEqxvOmLjj9oTzN5hV/bHhpX2ZlhBN8u/5Oh7J
            NejXxsRM6HaQu/AmgzkD/xIXqGCQ2xgPvCp4klrcW96jRj0ynoZ/wb9gsrQr4eed
            o5u0h+KnSnE418BXBHCzPaHG2PuqEuf5SB54y+mxt9v7xyrEm7ZmVOPTAxu+UEp/
            KyC9JlBQzspGJyMpLHAOBqaU2QGNsLGeCfk9Kfuml6Nv0BqZiarlSwkX0bBm/BFu
            HsjcKV0nvlvN7iKLyu0J2ZvXoVJJcc1ek2RE6KkWcvFopwnuRvn/AgzyOz0aDNzU
            aAEJAhANdC2e1/NBIFzkIB3A3Ls0uZAw6ZmyB9S9ZYU4cQYJF4JZx7xwIPX30aoM
            NhMqWvuwoW17SFftkRZ7kp9UC7FVjSGxTvPqjuJ+Co8VL6Gs0a5OvLtISwoVxKOw
            I0Ukqrwq1MIY
            =8D7Z
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-09-19T14:08:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAAgjpOipOPnzjlsRo6hi/Stv8K3lpvw9KqolAbyJCXKwa3
            zRzU4h7sgNjQCxPxnCWFxQukUBiVfDDNlvKcOPNa2vXbT88+i1qVHvIhItHJ5u9Q
            IyhyA3FW5v64m6FzD8dRYM0zcSm7p1tRldIztf2JtQjLneF5vHdRSylyISbelt+o
            M3uwLwl2na1J52/NwDAceqTYEBNp8JZEx+uXGDHaY31gTzx0pZnLSKvW6bXnYId3
            FhFHCVpCP4tghaLWJDKRigBPf9b3FXQoSFGXlLPk8BFAiAAumbEVBElDBbzvH7UI
            H4wJbJ4vSy1inW8z9rHc0HRTM0TegoZ6KVDzFsom89l3qOFDNlmsavbNbhh4e5Tk
            6x5BsfPDeEZQ3pVsXQeP2urPg3/LPC4m7FN3rHUYzFA8U3pskzkHj0f/KyPQmjJJ
            tjjZYKX/e99O4j9H/1HIfDcpIjnlwLz8DoTPUYHeQ9qxk10GXXD2YG6r2p0b2jD6
            nxz+65UYY/kwJEB4Pyz9R2Z1uMTXS2B+dJL4o6u59vjYdILLrb22xPyF5fKKGbCQ
            NYamQVa89C0hzHc0qND0YbEVVCtvhfFfUuipiC31zzFXbUGFJtQ1GkIG3bgAABJP
            dTQi9vNgnfZP3sUOlLjsfo+pqU5QAF7tMN2FlVILItLXDhHtETspSMDfqciths/U
            aAEJAhAt2OmyoW/+khW5stirCrMsjwyRPERoydFtLjBdbKwQIJpGJ2YGHmJsHcvs
            W1hmc3A8kvD+2gpK/X0MhJxPdjlP6G9WSwyvCEz42FAqMWaRYdzz7DVlnuDcW/fR
            +w6pvZn8Ne/M
            =Ii03
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    version: 3.13.1
