apiVersion: v1
kind: Secret
metadata:
    name: kitchenvault-secrets
    namespace: kitchenvault
stringData:
    #ENC[AES256_GCM,data:MZkISCyJpl+bpTWJdJutogBjcLM=,iv:wU9ZBginHCLO5braAfoM/BSxUTD01pc0/Bpm3wnhCGE=,tag:YMgbqD+z/Rjuz4/IeCPt1A==,type:comment]
    postgres-user-password: ENC[AES256_GCM,data:+XzOff0yGQ7jD85tu8rrHgxbXzyjGcec4+gQjCmvZ+n4HU0W2ulRR2sTwbZoda8=,iv:Jia9/xgI34r/ZvgnCFUZu1sLQrRHxadxIoz49tovNXA=,tag:t+fh5b4ZUpTa3abQjmYoTQ==,type:str]
    #ENC[AES256_GCM,data:2MIMRbasn5m3SPXAGIXNjOwkEMxVN6zrEtue3Ahm,iv:TngSmJabvzyjkj5+7u2HXsSZ8GNfjS0QpZh0zndBf4k=,tag:Ro/q7Kl/LBT+BAg5ibjSPw==,type:comment]
    ovh-ai-endpoints-access-token: ENC[AES256_GCM,data:u2amIDLyNY/R5dTPLtLckQYKNNik8QhZKap+15LwxX1haOeuYEuM/pJXNx9+5BGU+iy4RiP8QF5CaT6rSE4TRPSQMIMNJrPNE0Cf8iJjSzNsGb/gaVIIx9Hu3KEb70RnN2LrFnW034iKkgNjZ37WSpUEzFvoHRSykp8QnEB+cQ2nSCIftasl1/0a5iDDcKbhjT32JXEVNpE5wqG4HNBl043+oDyjNUuhRQYSBpz/vkFSym23VsKLT3wyc7vZ/XBpQkyOdSN/tfSFt3h6+INgnM8VeaDj+q11hSlmICkWJ/x8sMTMcE8f9UhGTH0+fW1cfH4VYDnkyrfXIxFGjhk3Mk4EPFDGhI46JJFgM+sa+W4kZyehUHqp3vzX,iv:Cqh1j8O7tXiP//IlMsJCBeslu0fZWnLnlL4GpodUiDU=,tag:uJeBaDPRNEY3AgoOgt4WPA==,type:str]
    #ENC[AES256_GCM,data:agiXqQT2CLTv8ooqR6ZKo+uQLZkr,iv:TamhrlukWRgectO3qktmfmQS2ebM/2vHyqKbly84gHw=,tag:f57nJFfC5IoGIxUmU7lkWA==,type:comment]
    COOKIDOO_EMAIL: ENC[AES256_GCM,data:QUltXJHFjm4vTRYYnCGFPJfrR8xWfA==,iv:LnOt3cJLaA4wCOiWQ36gLBkA5hNW0z+5Gp5onlbJrUI=,tag:ynFDtF7zkg3lcihZ1MsWeA==,type:str]
    COOKIDOO_PASSWORD: ENC[AES256_GCM,data:FtU2SYmBUa8xsFQjZ5bN+g==,iv:Onv36aRxO8d7cF1j9qae0tj/jxyXAnmkN2/awZqOibY=,tag:ptCjzjNu329dCVkGw2q1Yw==,type:str]
sops:
    lastmodified: "2026-05-13T20:31:43Z"
    mac: ENC[AES256_GCM,data:aAxjZVB/2fGNpkF2CAOjkxPsmeo8WLjMgRcUIZKJeJfZr020YC3jtjQS7PTZHPgMl7o5I+0YqtoErIyenXp8ef6TyNumGQG/pLb2Wn346NIkWviWa+58rZvOC+d952SMOIqpb84bnvQtNB8/SX7rmj20UWEqLyLmbm7vTLaci5Y=,iv:D3sIpmTuZmzXparnRsJMGN99hncWRpifm4C2sEj5n7s=,tag:3wij7q/Pyy18AH8ck1Z3ag==,type:str]
    pgp:
        - created_at: "2026-04-18T13:54:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4ARAAnxrH+GfN7B1Y9HBLaHy6fGEuH3gixhcW4gk56VBGZRZg
            J4XfHIJCu56bNLONGS2H4J65mYznOunDnn3/QjCtAgxa9fTQTsQffVjZxw8ewC9S
            Ez1omECj2t0yOkkRHy4iWETMEblmeZCrkY+HdV2/W3zvEfF5a/Wd3JIxa18YXwED
            xHRMCpub77WAFoUzGotb6FEpJrb4bVMDuN8eiJUYvQXyQQYmo6sBOCX4VxQZHSQ5
            10iIowDvpvfWMOADtxeJrLP29UN+G0YZzkAn6MsiU3Sk8Cjhr3oBAy6m9NX7pSOM
            7DGH9mOHuDFHvSoY3O7WHjqxgAGXMRWiNBPWHMRdcGYooNZ4fmMyK3rcGzIThyM7
            uIde+jB4X+BKLEa9xSMm5kL8z1eTFG4K4mu5ikogX5jFt1ymeHj+7qU4B8qwJuZB
            V/oLN/u7r5FDDoE2jpD4pknHk6O+3219PyTeYXAYg8MRPYQt4EExT9Hcd6HZSkQP
            PMS6jzlVejhYsvY8Y57u5wfjud8CzOHnYUtIPT8FSRd+UnTi6YUo8Vq5xPaizCB2
            xFU8dPRK5FhPZIEFUrGYizwEPzB5lULh49URi4iH3+GTnYLc10IKnRJhB60XFH6s
            lbvozgKrjZZPEOKDH/dNCOTivkMCjek6QpMfzzU7dE7OyPCqrAxo14VBkmEk8T/U
            ZgEJAhCFtqXX8pjcB/hEaoH0tD8YY8iHDWRC0aedQFZDOO8qTCcCbIcmxmteB3+S
            ReiKK/8Gsglt0LaV8XWy/33T3g3mYI3XtlZOopJTTHTCRhuDvKOUBe1tFtff13HC
            AnXHN2qHyA==
            =tvI6
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-04-18T13:54:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAAr4WRVrfInCJo2ZQVK/tww4NooFqoJB6EIa5fYR7NlVwA
            y4Tsnmy9/D16I8bMSVJz5EE5dPEA7hANV5HFQO6Wps9YhCXsgzGalakOjSaAYiSC
            pCBMQWJU56PRYM6l/1FMqGcHNd5UVJGfpReMofqkYlsKU6LalnQs1Mv/8EIMNEZw
            WKP0aQIdWHA38+4skaXTI8a246QGN+9i63/3WAjaOU85lRRypE1F9Bm/N2/QE5NK
            bMhPnlb7qhqhOAdp4EP9PIJdAa4scnZsn/ot084W+8siuLE8HPUiP6Ls71f0+ZgE
            UpruvNFdRC+pn7iqRmDx1NFUlQ8YJLlEH+ipWsbxPnzNKROo1HexFBKHe16Becjt
            OmjE+xm3J4hFerSpj4RItzszApfSehPU6puU2cRZj9kiBGbxO4KsuZ4WNZMCj1Fu
            n6Z7NH+RI/b8hnvEIRU1HQz6wP6AFkwtL28Pxac1zrkAs9ESktILuXR26o2CZM9z
            YbQAaAfjxn5mSHIfnkJClqbGp89hFlEpMyGsoz1SQncgEOD7soBLJK0sGefyfA7+
            mz8s+Fdm8Ss7WRPfUogP1mownphh6ygfke0P9OBC5SVpOgUktle5wzzGzwSaM4iA
            vT/LNQv30XGmuxNCO10AHn2alI4EWpu/vMG1K0Wy6HNzRhmMT9BIFyhnDx3XKJLU
            ZgEJAhA97qn+/wqXoNMq4dPo/mmhzT4vIjpR60xKTGoXhUdEuVupLGlibA4YnIY6
            pPNOa13AEeNq7QF8u6a3z7rDE5Xx49OS51Kf9L3H0BpnrrYjnZnxDKeSNCqeovsb
            H8vssY3OHQ==
            =Ve4y
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
