---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  mqtt-secure.server: |
    mqtt-secure.${SECRET_DOMAIN}:53 {
        hosts {
            192.168.1.38 mqtt-secure.${SECRET_DOMAIN}
        }
        cache 30
    }
