---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: linky
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: arm32v7/influxdb
      tag: "1.8"
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: "nfs-client"
      accessMode: ReadWriteOnce
      size: 30Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1024Mi
        cpu: 1000m
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: "${SVC_LINKY_INFLUXDB_ADDR}"
        externalTrafficPolicy: Local
    ## InfluxDB configuration
    ## ref: https://docs.influxdata.com/influxdb/v1.7/administration/config
    config:
      logging:
        level: error
      continuous_queries:
        log-enabled: false
      data:
        query-log-enabled: false
      http:
        log-enabled: false
    setDefaultUser:
      enabled: true
      user:
        username: "linky"
        password: ${SECRET_LINKY_INFLUX_DB_PASSWORD}
    initScripts:
      enabled: true
      scripts:
        init.iql: |+
          CREATE DATABASE "linky" WITH DURATION 730d REPLICATION 1 SHARD DURATION 1d NAME "teleinfo"
