---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      main:
        containers:
          main:
            image:
              repository: koenkk/zigbee2mqtt
              tag: 2.7.1
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 450Mi
                cpu: 1000m
              limits:
                memory: 512Mi
                cpu: 1000m
            securityContext:
              # Privileged securityContext required by USB devices accessed directly through the host machine
              privileged: true
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8080
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-forwardauth-authelia@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "zigbee2mqtt.${SECRET_DOMAIN}"
            secretName: zigbee2mqtt-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        globalMounts:
          - path: /app/data
        size: "1Gi"
      raspbee:
        enabled: true
        type: hostPath
        hostPath: /dev/serial0
      udev:
        enabled: true
        type: hostPath
        hostPath: /run/udev