---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: thomseddon/traefik-forward-auth
      tag: "2-arm"
      pullPolicy: IfNotPresent
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    middleware:
      enabled: true
    providers:
      google:
        enabled: true
        clientId: ${SECRET_GOOGLE_AUTH_CLIENT_ID}
        clientSecret: ${SECRET_GOOGLE_AUTH_CLIENT_SECRET}
    restrictions:
      domain: ${SECRET_AUTH_RESTRICTION_DOMAIN}
      whitelist: ${SECRET_AUTH_RESTRICTION_FIRST_ADDRESS}
    resources:
      requests:
        memory: 18Mi
        cpu: 10m
      limits:
        memory: 25Mi
        cpu: 20m
