---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: "arm64v8-5.2.6"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 190Mi
                cpu: 50m
              limits:
                memory: 265Mi
                cpu: 100m
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 7878
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "radarr.${SECRET_DOMAIN}"
            secretName: radarr-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
      media:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media
        globalMounts:
          - path: /data
