---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: radarr
  namespace: radarr
spec:
  interval: 60s
  scrapeTimeout: 15s
  module: http_app
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        check: web-app
      static:
        - http://radarr.radarr.svc.cluster.local:7878/
