---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: maintainerr
  namespace: maintainerr
spec:
  sourcePVC: maintainerr-data
  trigger:
    schedule: "0 3 * * *"
  restic:
    repository: maintainerr-volsync-restic
    copyMethod: Snapshot
    volumeSnapshotClassName: synology-snapshotclass
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
      monthly: 3
