---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: log-management
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 1m
  values:
    loki:
      config:
        auth_enabled: false

        limits_config:
          retention_period: 4320h  # 6 mois

        compactor:
          retention_enabled: true
          compaction_interval: 10m
          delete_request_store: boltdb-shipper
          working_directory: /var/loki/compactor

        schema_config:
          configs:
            - from: 2020-10-24
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: index_
                period: 24h

        storage_config:
          boltdb_shipper:
            shared_store: s3
            active_index_directory: /var/loki/index
            cache_location: /var/loki/cache

          aws:
            s3: s3://SECRET_LOKI_S3_ACCESS_KEY:SECRET_LOKI_S3_SECRET_KEY@minio.minio.svc.cluster.local:9000/loki
            s3forcepathstyle: true
            insecure: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      extraArgs:
        log.level: error
    promtail:
      enabled: true
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    grafana:
      enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      persistence:
        enabled: true
        storageClassName: "nfs-client"
        size: 1Gi
      env:
        GF_AUTH_ANONYMOUS_ENABLED: true
        GF_ANALYTICS_REPORTING_ENABLED: false
        GF_SECURITY_DISABLE_GRAVATAR: true
        GF_USERS_ALLOW_SIGN_UP: false
      adminUser: ${SECRET_GRAFANA_ADMIN_USERNAME}
      adminPassword: ${SECRET_GRAFANA_ADMIN_PASSWORD}
      sidecar:
        datasources:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-forwardauth-authelia@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - "logs.${SECRET_DOMAIN}"
        tls:
          - secretName: logs-tls-secret
            hosts:
              - "logs.${SECRET_DOMAIN}"
