---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: "arm64v8-4.0.0.748-ls220"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 256Mi
                cpu: 500m
              limits:
                memory: 512Mi
                cpu: 1000m
      transmission:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/transmission
              tag: "4.0.5"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
              USER: ${SECRET_TRANSMISSION_USER}
              PASS: ${SECRET_TRANSMISSION_PASSWORD}
            resources:
              requests:
                memory: 128Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 500m
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8989
            protocol: HTTP
      transmission:
        enabled: true
        controller: transmission
        ports:
          http:
            enabled: true
            port: 9091
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: sonarr-tls-secret
      transmission:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: transmission
        tls:
          - hosts:
              - "transmission.${SECRET_DOMAIN}"
            secretName: transmission-tls-secret
    persistence:
      config-sonarr:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          main:
            main:
              - path: /config
                readOnly: false
      config-transmission:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          transmission:
            main:
              - path: /config
                readOnly: false
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteMany"
        size: "200Gi"
        globalMounts:
        - path: /data
          readOnly: false
