---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tvheadend
  namespace: tvheadend
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      main:
        containers:
          main:
            image:
              repository: nextpvr/nextpvr_arm32v7
              tag: stable
              pullPolicy: Always
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 128Mi
                cpu: 1000m
              limits:
                memory: 256Mi
                cpu: 1500m
            securityContext:
              # Privileged securityContext required by USB devices accessed directly through the host machine
              privileged: true
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_TVHEADEND_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8866
            protocol: HTTP
    persistence:
      dvb:
        enabled: true
        type: hostPath
        hostPath: /dev/dvb
        globalMounts:
          - path: /dev/dvb
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
      recordings:
        enabled: true
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/tv
      buffer:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: ReadWriteOnce
        size: "2Gi"
