---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb-home-assistant
  namespace: influxdb-home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: arm32v7/influxdb
      tag: "1.8.10"
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClass: "nfs-client"
      accessMode: ReadWriteOnce
      size: 50Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1024Mi
        cpu: 1000m
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: "${SVC_INFLUXDB_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
    ## InfluxDB configuration
    ## ref: https://docs.influxdata.com/influxdb/v1.7/administration/config
    config:
      logging:
        level: error
      continuous_queries:
        log-enabled: false
      data:
        query-log-enabled: false
      http:
        log-enabled: false
    setDefaultUser:
      enabled: true
      user:
        username: "home-assistant"
        password: ${SECRET_DEFAULT_USER_INFLUX_DB_PASSWORD}
    initScripts:
      enabled: true
      scripts:
        init.iql: |+
          CREATE DATABASE home_assistant
