---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: influxdb-home-assistant
  namespace: influxdb-home-assistant
spec:
  sourcePVC: influxdb-home-assistant-influxdb2
  trigger:
    schedule: "30 2 * * *"
  restic:
    repository: influxdb-home-assistant-volsync-restic
    copyMethod: Snapshot
    volumeSnapshotClassName: synology-snapshotclass
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
      monthly: 3
