apiVersion: batch/v1
kind: CronJob
metadata:
  name: spotdl-update-playlist
  namespace: spotdl
spec:
  schedule: "30 1 * * *" # Tous les jours à 01h30 UTC
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                    - "true"
          containers:
            - name: spotdl-update-playlist
              image: spotdl/spotify-downloader:v4.4.3
              imagePullPolicy: IfNotPresent
              command: ["/bin/entrypoint.sh"]
              volumeMounts:
                - name: script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
                - name: media
                  mountPath: /music
            - name: spotdl-vpn
              image: ghcr.io/qdm12/gluetun:v3.41.1
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: "Europe/Paris"
                - name: VPN_SERVICE_PROVIDER
                  value: "cyberghost"
                - name: OPENVPN_USER
                  value: "${SECRET_VPN_USERNAME}"
                - name: OPENVPN_PASSWORD
                  value: "${SECRET_VPN_PASSWORD}"
                - name: UPDATER_PERIOD
                  value: "24h"
                - name: SERVER_COUNTRIES
                  value: "Belgium"
                - name: HEALTH_VPN_DURATION_INITIAL
                  value: "30s"
                - name: HEALTH_SUCCESS_WAIT_DURATION
                  value: "30s"
              volumeMounts:
                - name: media
                  readOnly: true
                  subPath: spotdl/vpn
                  mountPath: /gluetun
              securityContext:
                privileged: true
                capabilities:
                  add: ["NET_ADMIN"]
              resources:
                requests:
                  memory: 256Mi
                  cpu: 250m
          volumes:
            - name: script
              configMap:
                defaultMode: 0700
                name: update-all-playlist-script
            - name: media
              nfs:
                server: 192.168.1.10
                path: /volume1/media
          restartPolicy: OnFailure
