---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: "v8.4.62"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              LOTSOFDEVICES: true
            resources:
              requests:
                memory: 1024Mi
                cpu: 250m
              limits:
                memory: 2048Mi
                cpu: 500m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_UNIFI_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "unifi-controller"
        ports:
          http:
            enabled: true
            port: 8080
            protocol: HTTP
          https:
            enabled: true
            port: 8443
            protocol: HTTP
          speed-test:
            enabled: true
            port: 6789
            protocol: HTTP
      udp:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_UNIFI_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "unifi-controller"
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
          l2-discovery:
            enabled: true
            port: 1900
            protocol: UDP
    persistence:
      unifi:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: "ReadWriteOnce"
        size: "10Gi"
