---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: crowdsec
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: crowdsec-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      repository: crowdsecurity/crowdsec
      pullPolicy: Always
      tag: "v1.5.5"
    container_runtime: containerd
    tls:
      enabled: true
    config:
      capi_whitelists.yaml: |
        cidrs:
        - 192.168.1.1/24
    agent:
      acquisition:
        - namespace: networking
          podName: traefik-*
          program: traefik
      env:
        - name: PARSERS
          value: "crowdsecurity/cri-logs"
        - name: COLLECTIONS
          value: "crowdsecurity/traefik"
      persistentVolume:
        data:
          enabled: true
          storageClassName: "nfs-client"
          size: 1Gi
        config:
          enabled: true
          storageClassName: "nfs-client"
          size: 100Mi
    lapi:
      dashboard:
        enabled: false
        ingress:
          host: dashboard.local
          enabled: true
      resources:
        limits:
          memory: 500Mi
          cpu: 1000m
        requests:
          cpu: 200m
          memory: 250Mi
      persistentVolume:
        config:
          enabled: false
      env:
        - name: ENROLL_KEY
          value: ${SECRET_CROWDSEC_ENROLL_KEY}
        - name: ENROLL_INSTANCE_NAME
          value: "k3s_cluster"
        - name: ENROLL_TAGS
          value: "k3s at home"
