---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: crowdsec
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: crowdsec-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      repository: crowdsecurity/crowdsec
      pullPolicy: Always
      tag: "v1.6.1-1"
    container_runtime: containerd
    tls:
      enabled: true
    config:
      capi_whitelists.yaml: |
        cidrs:
        - 192.168.1.1/24
      parsers:
        s02-enrich:
          whitelist-local.yaml: |
            name: crowdsecurity/whitelists-local
            description: "Whitelist for local network"
            whitelist:
              reason: "local IP"
              cidr:
                - "192.168.1.0/24"
    agent:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      acquisition:
        - namespace: networking
          podName: traefik-*
          program: traefik
      env:
        - name: PARSERS
          value: "crowdsecurity/cri-logs"
        - name: COLLECTIONS
          value: "crowdsecurity/traefik"
      persistentVolume:
        data:
          enabled: true
          storageClassName: "nfs-client"
          size: 1Gi
        config:
          enabled: true
          storageClassName: "nfs-client"
          size: 100Mi
    lapi:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboard:
        enabled: false
      resources:
        limits:
          memory: 150Mi
          cpu: 500m
        requests:
          cpu: 50m
          memory: 125Mi
      persistentVolume:
        data:
          enabled: true
          storageClassName: "nfs-client"
          size: 1Gi
        config:
          enabled: true
          storageClassName: "nfs-client"
          size: 100Mi
      env:
        - name: ENROLL_KEY
          value: ${SECRET_CROWDSEC_ENROLL_KEY}
        - name: ENROLL_INSTANCE_NAME
          value: "k3s_cluster"
        - name: ENROLL_TAGS
          value: "k3s"
