---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebridge
  namespace: homebridge
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: homebridge/homebridge
              tag: "2024-01-08"
              pullPolicy: IfNotPresent
            env:
              # -- To interact with the self-signed certificate with local Tydom
              NODE_TLS_REJECT_UNAUTHORIZED: 0
              TZ: Europe/Paris
              PUID: "1000"
              PGID: "1000"
              HOMEBRIDGE_CONFIG_UI: 1
            resources:
              requests:
                memory: 280Mi
                cpu: 150m
              limits:
                memory: 350Mi
                cpu: 250m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_HOMEBRIDGE_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8581
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "homebridge.${SECRET_DOMAIN}"
            secretName: homebridge-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          main:
            main:
              - path: /homebridge
