---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gluetun-test
  namespace: gluetun-test
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.37.0
              pullPolicy: Always
            env:
              TZ: Europe/Paris
              VPN_SERVICE_PROVIDER: cyberghost
              OPENVPN_USER: ${SECRET_VPN_USERNAME}
              OPENVPN_PASSWORD: ${SECRET_VPN_PASSWORD}
              UPDATER_PERIOD: 24h
              SERVER_COUNTRIES: Belgium
            securityContext:
             capabilities:
               add: ["NET_ADMIN"]
            resources:
              requests:
                memory: 128Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 250m
          curl:
            image:
              repository: quay.io/curl/curl
              tag: latest
              pullPolicy: Always
            command: ["sleep", "infinity"]
            resources:
              requests:
                memory: 32Mi
                cpu: 125m
              limits:
                memory: 32Mi
                cpu: 125m
    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          main:
            main:
              - path: /gluetun