blueprint:
  name: RFID Card → Music Assistant (Track Selector)
  description: >
    Carte RFID individuelle.
    Sélection d’un média via le navigateur Music Assistant.

  domain: automation

  input:
    tag_id:
      name: Tag RFID
      selector:
        text:

    media_content:
      name: Lecteur et média associé (Track / Album / Playlist)
      selector:
        media:

mode: restart

trigger:
  - platform: tag
    tag_id: !input tag_id

variables:
  selected_media: !input media_content

  target_player: >
    {% if trigger.event.data.device_id == states('input_text.lecteur_rfid_salon') %}
      media_player.chromecast_hi_fi_2
    {% elif trigger.event.data.device_id == states('input_text.lecteur_rfid_etage') %}
      media_player.google_nest_palier_2
    {% else %}
      none
    {% endif %}

condition:
  - condition: template
    value_template: >
      {{ target_player != 'none' }}

action:
  - service: media_player.play_media
    target:
      entity_id: "{{ target_player }}"
    data:
      media_content_id: "{{ selected_media.media_content_id }}"
      media_content_type: "{{ selected_media.media_content_type }}"
