blueprint:
  name: RFID Card → Music Assistant (Track Selector)
  description: >
    Carte RFID individuelle.
    Sélection d’un média via le navigateur Music Assistant.

  domain: automation

  input:
    tag_id:
      name: Tag RFID
      selector:
        text:

    music_assistant_player:
      name: Player Music Assistant (pour parcourir la bibliothèque)
      selector:
        entity:
          domain: media_player

    media_content:
      name: Musique (Track / Album / Playlist)
      selector:
        media:
          entity: !input music_assistant_player

mode: restart

trigger:
  - platform: event
    event_type: rfid_card_scanned

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.tag_id == !input tag_id
         and trigger.event.data.player != 'none' }}

action:
  - service: media_player.play_media
    target:
      entity_id: "{{ trigger.event.data.player }}"
    data:
      media_content_id: "{{ !input media_content.media_content_id }}"
      media_content_type: "{{ !input media_content.media_content_type }}"
