blueprint:
  name: RFID Card → Music Assistant (Track Selector)
  description: >
    Une carte RFID individuelle.
    Permet de sélectionner une track / album / playlist Music Assistant
    via une liste déroulante dans l’UI.

  domain: automation

  input:
    tag_id:
      name: Tag RFID
      description: ID du tag RFID (copié depuis les outils développeur)
      selector:
        text:

    media_entity:
      name: Musique (Track / Album / Playlist)
      description: Sélectionne un média depuis Music Assistant
      selector:
        entity:
          integration: music_assistant

mode: restart

trigger:
  - platform: event
    event_type: rfid_card_scanned

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.tag_id == !input tag_id
         and trigger.event.data.player != 'none' }}

action:
  - service: media_player.play_media
    target:
      entity_id: "{{ trigger.event.data.player }}"
    data:
      media_content_id: "{{ state_attr(!input media_entity, 'media_content_id') }}"
      media_content_type: "{{ state_attr(!input media_entity, 'media_content_type') }}"
