apiVersion: v1
kind: Secret
metadata:
    name: go2rtc-secrets
    namespace: go2rtc
stringData:
    NVR_USERNAME: ENC[AES256_GCM,data:RHZgIrGR,iv:DNghFAcjySjmqy+kuQYfsmJj7PcVgd8mO5wcgb2QsCg=,tag:njG4AjiBAroci8R32OUCtQ==,type:str]
    NVR_PASSWORD: ENC[AES256_GCM,data:e/WZWn8UmxZyVrudaHke,iv:2xWg6nKtcqvmlYEd7VuybaDjSup+H+WWz0WGhNostqo=,tag:YPcnG1xGzZVEGv1YMZrpiw==,type:str]
sops:
    lastmodified: "2026-05-17T14:07:32Z"
    mac: ENC[AES256_GCM,data:XbKNzJiUv0/4fJXAaSvgEmJuFLbbb1O+Qp9D3z1szntHTLoNlZyFakZmF1J90c8feC05fGbLW92Q/CMdSVld90u+09OXeh2P0YfMSZk8fiiw1MrylHNApN9xKtCOR3N7iO5khfjUkHt5VXOHiyAYRNmC+ZR1hv+wGgAYIsyUKyI=,iv:5KbXCzvJIEvU1EaBaB79SD2S1Ot6lQCO2rlkgmzLX/c=,tag:9Q5WCUD355lEQ4qhJ1tveA==,type:str]
    pgp:
        - created_at: "2026-05-17T14:07:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ/+LNM04Zu/Uupiby2iRRPQo9tr7WvmavaHs/Iuhk7Q16C2
            1CGkDdxM098aE10s19hV4716Yok3FbDDf1NTtiLElyfu+o1PTODmmUsMGnTaKfM2
            WOCWkxJbfJrx6qiLzQarAUBvRe6hW7dbpkIkxtPbNPB0sismvCcsnVcDE+x39oye
            UN5Wc0ug7Q6Q63oIjGQqOjaAm2qVtCG4y2WgIIT0ruzQknuvn5vI4HPFHrNagx/J
            FDgBPgbVScVs5/KhNVj77UuA0fyoxILzjddXHUUWSNz4toss1gHBjZYlQyNbGpkT
            k/88T6ZMnGN6GBoRv5fqUWVloGVC2P2ngiAmRA0DtNs/6QHH+kg3l8kIvzn/MWKz
            8tYA6ZN1dt+u23DG3INhNK413xolwbQYXTMlX3aQB8RLU6zUGOsgUeVI7DoSF4KK
            PLKBEdL8gEnIaJifAF7g2otwcuXbKAu+M7ytTC/hU13FocZo5tyxIIW/5WNUHSUj
            90l3Ya88DcswYhQDP0zfHRvfdMijvzT75emyOoMjPrMy+1wtxqLzAVYKpN7bByLJ
            3tbxVoaAAnvKDE8SCLqMrCYzOPxH5RjNTjhPy2/xZiShqYU2dXTmu4M5ZEGawXJb
            fy/DntgfWfPzKvxcoJ1CimnMnYDOHLOrUE9fgrtptqzpO3ZdIByU8/IWiERPzoTU
            ZgEJAhAbryY8eGV21Xx4sI2i6Tvm807iOQaKYuq1zERBI+EPcKH6XHpU2lmkrQNP
            dE1HIOhp439JsmTW+hC9Wx6x5vzR+L7PU5x9z8abUgzC9a8xwUHHNyDNHwyEPrHK
            /r1gm30PHQ==
            =GLH1
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-05-17T14:07:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAAgZhCJ0aTB9v11kjjbqjdUCBFwT0MpRZnx+YBLuipxxGE
            kg1x9tiOq4syq8YjQdAj7RTVSXg0We0932Yu55KNB4CG9MvBNRI17rEwGLCiXdsv
            UnlJe8SNk4dLxWm2TZexEwR1rmtYriG+aaITKo46uBPynazDUkvowmTRaYxgGUuh
            GeqzK4e1pOXN5Qmo8/1GrbhMMSDOjXC5TiLabVkRjgQY7RlCCYtgkIJxzIHDh3Zn
            YuwDTwRvPXO8dD0W5iSGnSlgQ7vqdLFLfYVyOnaR2MCIeveZf51KbftWRM4RttI4
            0Gy1Eh6SVLK3r6HkyjuRmwrRvNK0kfSKJ9+Isj+nJmYHvUWrf8wCPFBcGitOoKPH
            W2hmogMd8T+K2coyRIjC9UH8shn/aoTdV8IljltTbexfqkQ8sV+rCAyRMBnRlFlI
            EoMl4GkhoYs+qCBn6TYQSeVWdBMAC+YBQ/c9oIc+Y28vRlIcMmiYIPOQYHkJv4jg
            q6QDPUmfMvVU04Y9DNL5iiLj6Zk175UOWcqyq25BcecWzOj+n23b/UN/VNyqG5bf
            UcxD8qdCq+zbj6kNp/ahYuuf/gVeoKZ0mY1UCPosCbYJoNzNx3wba6T3S3eacfse
            nq3fYOjLlj9jRLfZbPPHSZspuBQDXlCSBW+hxE1CzsNbjnNWfCVTA19LWpAS2nDU
            ZgEJAhCjP3xiKcYBzZVIh641tty36UKpNWVv6RNXal3QCYANxhjxrsail8Tz+qw9
            uNkDPj0npejzy6I+F0Qu7eAF+H7fxQRj26+GdAqosnmBUm3i1Ik9J1t6AsSAXHbL
            BhuT+PXGsg==
            =aLMT
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
