apiVersion: batch/v1
kind: CronJob
metadata:
  name: bitwarden-db-backup
  namespace: restic
spec:
  schedule: "15 1 * * 0" # Tous les dimanches à 1h30 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restic-bitwarden-db
              image: ghcr.io/seblaporte/restic
              imagePullPolicy: Always
              env:
                - name: RESTIC_PASSWORD
                  value: ${SECRET_RESTIC_PASSWORD}
                - name: RESTIC_REPOSITORY
                  value: ${SECRET_RESTIC_REPOSITORY}
                - name: OS_STORAGE_URL
                  value: ${SECRET_RESTIC_OS_STORAGE_URL}
                - name: OS_AUTH_TOKEN
                  value: ${SECRET_RESTIC_OS_AUTH_TOKEN}
                - name: MYSQL_USER
                  value: bitwarden
                - name: MYSQL_PWD
                  value: ${SECRET_BITWARDEN_DB_PASSWORD}
                - name: MYSQL_DB
                  value: "bitwarden"
                - name: MYSQL_HOST
                  value: "192.168.1.10"
                - name: MYSQL_PORT
                  value: "3336"
              command: ["/bin/entrypoint.sh"]
              volumeMounts:
                - name: script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
          volumes:
            - name: script
              configMap:
                defaultMode: 0700
                name: mysql-backup-script
          restartPolicy: OnFailure
