apiVersion: batch/v1
kind: CronJob
metadata:
  name: volume-backup
  namespace: restic
spec:
  schedule: "30 14 * * 1" # Tous les lundi à 14h UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: restic-volume
              image: ghcr.io/seblaporte/restic
              imagePullPolicy: Always
              env:
                - name: RESTIC_PASSWORD
                  value: ${SECRET_RESTIC_PASSWORD}
                - name: RESTIC_REPOSITORY
                  value: ${SECRET_RESTIC_REPOSITORY}
                - name: OS_AUTH_URL
                  value: ${SECRET_RESTIC_OS_AUTH_URL}
                - name: OS_IDENTITY_API_VERSION
                  value: "${SECRET_RESTIC_OS_IDENTITY_API_VERSION}"
                - name: OS_TENANT_ID
                  value: ${SECRET_RESTIC_OS_TENANT_ID}
                - name: OS_TENANT_NAME
                  value: "${SECRET_RESTIC_OS_TENANT_NAME}"
                - name: OS_USERNAME
                  value: ${SECRET_RESTIC_OS_USERNAME}
                - name: OS_PASSWORD
                  value: ${SECRET_RESTIC_OS_PASSWORD}
                - name: OS_REGION_NAME
                  value: ${SECRET_RESTIC_OS_REGION_NAME}
                - name: OS_USER_DOMAIN_NAME
                  value: "Default"
                - name: OS_PROJECT_DOMAIN_NAME
                  value: "Default"
              command: ["/bin/entrypoint.sh"]
              volumeMounts:
                - name: script
                  mountPath: /bin/entrypoint.sh
                  readOnly: true
                  subPath: entrypoint.sh
                - name: nfs
                  mountPath: /k3s
                  readOnly: true
          volumes:
            - name: script
              configMap:
                defaultMode: 0700
                name: volume-backup-script
            - name: nfs
              nfs:
                server: 192.168.1.10
                path: /volume1/k3s
          restartPolicy: OnFailure
