---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yubal
  namespace: yubal
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:b3255e7dfbcd10cb367af0d409747d511aeb66dfac98cf30e97e87e4207dd76f
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "mkdir -p /config && chown -R 1000:1000 /config"
            volumeMounts:
              - name: config
                mountPath: /config
        containers:
          main:
            image:
              repository: ghcr.io/guillevc/yubal
              tag: "0.6.2"
              pullPolicy: IfNotPresent
            env:
              YUBAL_TZ: Europe/Paris
              YUBAL_FETCH_LYRICS: false
              YUBAL_CONFIG: /config
              YUBAL_DATA: /data
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
            resources:
              requests:
                memory: 128Mi
                cpu: 250m
              limits:
                memory: 265Mi
                cpu: 250m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  periodSeconds: 5
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8000
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-forwardauth-authelia@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "yubal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "yubal.${SECRET_DOMAIN}"
            secretName: yubal-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: "ReadWriteOnce"
        size: "2Gi"
      data:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/media/music
