---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: yubal
  namespace: yubal
spec:
  sourcePVC: yubal-config
  trigger:
    schedule: "30 3 * * *"
  restic:
    repository: yubal-volsync-restic
    copyMethod: Snapshot
    volumeSnapshotClassName: synology-snapshotclass
    pruneIntervalDays: 14
    retain:
      daily: 7
      weekly: 4
      monthly: 3
