# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3CBAluHl4Ls5ex6C7nkoUm9taW+nGhYq/g==,iv:8lyqePjwQL9BwrSltFIgwHXaqswWbSxgzmJjkoF79w0=,tag:PnwimMrLnwUdDdznf7XrhQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SjPwDcD4tmzd1UrGgl8ISC2frIk+,iv:8pYjqtXKHwOfmN3oCEFPFOk/PGoOjX6Pl4+8yVXX2qE=,tag:oDrw1sfTsMGIc0AKf9AXzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-30T09:44:56Z"
    mac: ENC[AES256_GCM,data:ws47re5VFmdcUnFsiq9s6FngeVcjjvmBALSjkV1CDqvdBrn/ETt41Lt1Byj1j0tkH3l6e6khH29jGqbnb3J/rZR6XjO43nEnEexF8Dth9Lc/qMZuMyIUi8HMkiV7IeyJD4/hZuoILOoVsXxDPct3h98NGJ2lEX+WgCR89pX2PzM=,iv:/pLmY+fIqh63O+MT9efdTWEqrlRJt9o/9nsSp/swW+g=,tag:I5OaqcVbM+BBpizxeRcfuQ==,type:str]
    pgp:
        - created_at: "2021-08-30T09:44:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ/+JN7QZ47m6lUOmIabH5LV2bROAKh6y7I7F9KufYrhbmFj
            htwM9lTtssMeHaMV32GgOVoa3CPGQ/su9YhQmqPzZCsjYc9esvr6XxOv7AjYnDwx
            4jRWjITo/Aw/bWgSqncSjhcYbGLAvS1wILbnaV+XYr9sm6o3XKdkwL0d50Ec6Qrs
            dk1LFVpc68qYZx3dDjixJlIQ/MJB8pE877OXYYysJd9EloCVGe0ivZmYXoFXt/jC
            03y7ylHAEyqJZtm/5B1WZxamgoll7GOoMz08Mq88SJuXr9VtKjoDwyCGmwE175jw
            O3UCP5AACJ4VV40c5ACkJyy8d1LaQOF7u92A2dKunCw66zlfaR61T9WGtsfhCCPg
            3qz3zG9M89xW4t72n1QkxZuC/RAGxdsS85EoonN9VdEz9/vNsiZPKeG2JQHTCSqU
            OJxeJhFqRYQLqnOPaqqUd0zvh3id6l/G/dokoyd2M6okn19AoHUfjD+dkWu0o9a6
            THH5c9fpE9T3zpBACV9pN6cyfjkT2835K5C/Sp/kkbhWfcEd8JK65DiQI9ec2TW6
            AzH6w573sbBGDeUKytK0MLUEnk7eXDemmleOyxBhDxUmSqxwSr6rLVOJUsa4q08M
            hsgHsWLHP0DsKPygyO9OBstP2vQcNbH1jfKT7W1oOnz3MJM5hRnE0kyPBSNnD03U
            aAEJAhVtbh+PkQLc2C78JPCkSjlgIS2j8kCGQg4LXF6EDFcItd3YnIXveLGPHBYM
            5dY+K1i04VIDlb346UarNu/O1Ifv9zUgKbcu3FrDMri86PDMj6J4fqLzJYZXMkQt
            7oUA9ouosRCY
            =gy/N
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2021-08-30T09:44:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2AQ//WSvloPxfOC7c5a4gTNIZ5XMZlE74T0pJsI/0EwMXNs43
            0Dsvxp34/zO9kLcSw7NFlOh1g+PO+EqX7Dbfobda/lpCE0xILtLq67V3LHRlWwyt
            QRG2qU3u3z83BO1dDf0jz3hTWnJZs/endzQyzgUkrfqsT/hRnkhjp2irXyedVOcd
            bA4ODh5DdPw2jFSEeHe/HplPxIKu0po0DhdtW2hoOV8XscaTqlMcTlGQnbTk2sCo
            E756sOY2Pcnnpl1Yxv40AfcxTNpJkoNcyPWWahQbJvozatS/IIwIQ3iN170tlQ/x
            7pXSj/XBYlDVuqtkRSrWtPGs2RIiihwymDrhEm6I1umj+5MTnC7zEW+Qyr/bMV7d
            oh6y/Sujz316mX3B+bwRZnyF/Le7C8X+jFE+Ktgl9d6uJ1FxklzS8ZLbT23U3m/P
            XnGeLRfquHTdKQwiLE4kH/zrAn1eqBweWTxwHn7snqv2McOSK0IIl0z28oQ014Y6
            qvfOh/qkehAxLWvu8p13KaREf2T1lm604XFnGa68wNFbFkybZAS7fpBPgHBIb+Mt
            HMe9HMRHRDSmOWp9U/fe8aps8kKLZzwDye01XhzG1AdQtEnVaQdU5UQaJJFEFLaE
            nyu+Leg84rj5VzGIbCvcUPGXaGh2Sp0qFrWQLXvtDZloL41FPkENeCPSbPt8IZfU
            aAEJAhXy6Kjeq+zONpqpi7vZGKPu7gynm7ikr4VeMtcu7yE2u1px/7rXfEUi2dlr
            KJaPkAbAmXOIP2aAq+hb223GJWIbwdcQScqb+g9EfMoGYYhX5yqGtdhftRTzddE4
            b9NiWY9LoXT4
            =4vP2
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
