# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WZ/2tvhewfUMCa3u29ufgVbhxzwMGGkCOg==,iv:eXNNhC7Bt6A/26qxyUjY+bSwai1SOPc4zMAzhTITMg0=,tag:GEAhpZKYH0anjaMtsJVDxg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:lF6jVLtHWIMpue3xsTl5T1slhHLsWQuPgL0=,iv:lTUio7x9RkPerk2aQ/6o3X+UBY4NEUZgQHyIVwKu5P0=,tag:6JgSH7dru3UXG8tSFgzxSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-30T19:55:54Z"
    mac: ENC[AES256_GCM,data:BtoLArG+w5s4sOjjzpwd4tofCvG7FryfUZIyQ1nOSM48wMrM6DE05S1BfEa3oqRQh8797dUy7lBpvoOvBMmpClsPQ53bMPC9OVF9k7PBcn3Q3WyjBr5FkD5he/pglnkLadfa49HrQWj7Pn5XgAVDlzjctmss2yVxrkZPTI9J7I4=,iv:VR2UHTQPg+Cs6lluTpgpU+CXPtql/OTN6OhcWB467IU=,tag:7Cgvq766zjY2bMBrS2jKqA==,type:str]
    pgp:
        - created_at: "2021-08-30T19:55:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ//clsCsFBMonsJLryOWDLfd6kL2z/3VJSn+AbQEL3dF+jP
            Et9DZOTsfinS9QCnlBo2m7RNKsdnSYeFIWClu5IP0oboyA8TM0FQpz/HRxqybqQt
            OvLtZUrkSjgl7+eVRl3535T9ZLh/BRCZi5KsNMSSpJCR9EqTUeEYpIRceraQ+K9d
            co8q9z4nR/vYn//wscjFvIb4UyWMmw8PwgpemBEISbtOnfeI1I8Yvy/ImExtXPP+
            rSVGca2M2QQ4SEJnYFZJdls9gVksbbvHo7VLAVf7ynBgYjdBpXAWnA/EXCW4LsBN
            kygxHWVAgoklvlTXcEO7WbejfPfrVgju/SQ/QA8mpUs7z8vDBSYzfEtIkYkudx5O
            YCr3xYF+m1saP+/jtHw3HCSJGsBtIroq3iNgDI/FfqhFftajyco+3y2ccdbJlx5T
            OLAPo2tGUrCb4KDWLUGteTtabTyAlCpoeyJj4GwLQHDu1J6JLa0x71XYgAfYNu/o
            3RWO2IBCtBa49PSm/E+N/hsICW7kACPFxEg6vG0yHU+PQjBFcS/HnwgdYX6YOlKY
            2vvZFP7Lak9iBQIq+cjuql2PMRozTXuUWHoK0ZmY4DxceNsbY0+KxQ3kBeiihv3k
            wOC7AK1m8zk7rf9mpWp5MI5Hz1w5gXd4Lz7KsgdH5+ZEO2PXM+kHiWAsxRyfmezU
            ZgEJAhUkzrL/ci/mjGftIoRhQF6Jr3FxpznBU+8Znm8MuZOgfGgQvynoeihcoH5t
            3qn9SnKXT6ulWxzfMaKUH6Bo52tidH818PMMRtIW2TNKWXCCUdykuBDn19MYB/5d
            KEO8G7sLyA==
            =DU8F
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2021-08-30T19:55:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAAgyLgGGmy6mAjrcrVR2wVaiXsgTSWwN+/b9HRjDQ6WECB
            mbyUJM0RTy2h9xyuKylV854Z5mtQzy3fKMsJSSLjaXGlXcM5KW10qrfybNKm/qNc
            9PHmt374ccw2Qzn+wpOS+FYJJi1hAE3ND1Xm677ECEGXV0JWkHgJegf8dRTyjXF9
            g9HMJWooBgOLz2wnOf1NZ4CeMBub/3SN8DHRkZEhHO9huPnWEol8NEOiTq/1Nok3
            zeAM9wP/lCvmKC3BJ6CLveT64vm6urXVXXpT90hHMudfpgZ2Wico3qomudETrDDI
            gEy0X46rR0GHxDfODrnzYcK75YfAagNkZuYYEOB4YZxPf4zmhU1yGXRoZt83zm6z
            C25SUtLZgclT6jfG5Vzo3TaveoE8nLr5JTku3jTP3AWqSpYhZypACkRrfO1i9iL+
            mPM/tDIjfJikc2qxrEp7tQ5fgZ0kPyNhbdNFrbZZ7hgIlddEGkwJ4vryATQe1m1K
            lTF/W4afNOkHaeV6vkgdOk8a+IxZeq1dglNhveW8PbP8BVPnpwAXSPBvz2MKK+/7
            g5Lm2cPjievyTZMkUS0CxseB2eWsN8G5Ae0OizaMsIXTfWOgta+VMM05yPtOfHkJ
            fCpaWLZEt9Zw7kDIkt55bEAUTeyrBGQ5ms7rSxC9OxUsncgv5Ctvlk+QAgS1aMHU
            ZgEJAhUThjWjuZw8TxeR/p3k3O/mcLzlZW2eBEx0hGiecwcYhTUhIxL5pkf//yYq
            POjyoo/TFmJb4aWR7BNQITk4ksqLP/W+31FnpkZuCnZZ5Mk65BmJCboreB62qnL7
            amAGw4Expg==
            =XmKA
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
