---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  interval: 60s
  scrapeTimeout: 15s
  module: http_app
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        check: web-app
      static:
        - http://jellyseerr.jellyseerr.svc.cluster.local:5055/
