---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/music-assistant/server
              tag: "2.7.8"
              pullPolicy: IfNotPresent
            resources:
              requests:
                memory: 1024Mi
                cpu: 250m
              limits:
                memory: 2048Mi
                cpu: 500m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_MUSIC_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8095
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "music-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "music-assistant.${SECRET_DOMAIN}"
            secretName: music-assistant-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: ReadWriteOnce
        size: "2Gi"
