---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
  namespace: music-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      hostNetwork: true
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/music-assistant/server
              tag: "2.4.4"
              pullPolicy: IfNotPresent
            env:
              LOG_LEVEL: warning 
            resources:
              requests:
                memory: 1024Mi
                cpu: 250m
              limits:
                memory: 2048Mi
                cpu: 500m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 8*60=480 seconds to start up before it fails
                  periodSeconds: 8
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 8095
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-traefik-forward-auth@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "music-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "music-assistant.${SECRET_DOMAIN}"
            secretName: music-assistant-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: ReadWriteOnce
        size: "5Gi"
      music:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/media/music
