---
apiVersion: v1
kind: Secret
metadata:
  name: music-assistant-volsync-restic
  namespace: music-assistant
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${SECRET_RESTIC_REPOSITORY}volsync/music-assistant/music-assistant"
  RESTIC_PASSWORD: "${SECRET_RESTIC_PASSWORD}"
  OS_AUTH_URL: "${SECRET_RESTIC_OS_AUTH_URL}"
  OS_IDENTITY_API_VERSION: "${SECRET_RESTIC_OS_IDENTITY_API_VERSION}"
  OS_TENANT_ID: "${SECRET_RESTIC_OS_TENANT_ID}"
  OS_TENANT_NAME: "${SECRET_RESTIC_OS_TENANT_NAME}"
  OS_USERNAME: "${SECRET_RESTIC_OS_USERNAME}"
  OS_PASSWORD: "${SECRET_RESTIC_OS_PASSWORD}"
  OS_REGION_NAME: "${SECRET_RESTIC_OS_REGION_NAME}"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_NAME: "Default"
