---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: "v2.7.1"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              DATABASE_URL: postgresql://linkwarden:${SECRET_LINKWARDEN_DB_PASSWORD}@192.168.1.10:5428/linkwarden
              NEXTAUTH_URL: https://linkwarden.home.sebastien-laporte.fr/api/v1/auth
              NEXTAUTH_SECRET: ${SECRET_LINKWARDEN_NEXTAUTH_SECRET}
              NEXT_PUBLIC_DISABLE_REGISTRATION: true
              DISABLE_NEW_SSO_USERS: true
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 512Mi
                cpu: 500m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 8*60=480 seconds to start up before it fails
                  periodSeconds: 8
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 3000
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "linkwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "linkwarden.${SECRET_DOMAIN}"
            secretName: linkwarden-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: ReadWriteOnce
        size: "20Gi"
        advancedMounts:
          main:
            main:
              - path: /data/data
