---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: navidrome
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
      hostNetwork: true
    controllers:
      main:
        containers:
          main:
            image:
              repository: deluan/navidrome
              tag: "0.53.3"
              pullPolicy: IfNotPresent
            env:
              ND_LASTFM_ENABLED: true
              ND_SCANSCHEDULE: "0"
              ND_LASTFM_APIKEY: ${SECRET_NAVIDROME_LASTFM_APIKEY}
              ND_LASTFM_SECRET: ${SECRET_NAVIDROME_LASTFM_SECRET}
              ND_LASTFM_LANGUAGE: fr
              ND_SPOTIFY_ID: ${SECRET_NAVIDROME_SPOTIFY_ID}
              ND_SPOTIFY_SECRET: ${SECRET_NAVIDROME_SPOTIFY_SECRET}
            resources:
              requests:
                memory: 256Mi
                cpu: 50m
              limits:
                memory: 350Mi
                cpu: 100m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_NAVIDROME_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 4533
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "navidrome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "navidrome.${SECRET_DOMAIN}"
            secretName: navidrome-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: "ReadWriteOnce"
        size: "10Gi"
      music:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/media/music
