---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
  namespace: matter-server
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: "6.6.1"
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 256Mi
                cpu: 500m
              limits:
                memory: 256Mi
                cpu: 500m
    hostNetwork: true
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_MATTER_SERVER_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 5580
            protocol: HTTP
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"