---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
  namespace: scrypted
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: scrypted
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: koush/scrypted
      tag: "v0.123.34-jammy-lite"
    hostNetwork: true
    resources:
      requests:
        memory: 1024Mi
        cpu: 800m
      limits:
        memory: 1300Mi
        cpu: 1000m
    probes:
      startup:
        enabled: true
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 100
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_SCRYPTED_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 11080
            primary: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "scrypted.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "scrypted.${SECRET_DOMAIN}"
            secretName: scrypted-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /server/volume
        size: "10Gi"