apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - prometheusrule.yaml
configMapGenerator:
  - name: trivy-operator-dashboard
    namespace: monitoring
    files:
      - trivy-operator.json=dashboard.json
      - trivy-image-updates.json=dashboard-updates.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
