---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slskd
  namespace: slskd
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: slskd/slskd
              tag: "0.24.4"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              SLSKD_SHARED_DIR: /music
              SLSKD_REMOTE_CONFIGURATION: true
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 265Mi
                cpu: 250m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  periodSeconds: 5
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        ports:
          http:
            enabled: true
            port: 5030
            protocol: HTTP
          soulseek:
            enabled: true
            port: 50300
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-forwardauth-authelia@kubernetescrd
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "slskd.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "slskd.${SECRET_DOMAIN}"
            secretName: slskd-tls-secret
    persistence:
      app:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: "ReadWriteOnce"
        size: "5Gi"
      music:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/media/music
