---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joal
  namespace: joal
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                      - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: anthonyraymond/joal
              tag: "2.1.36"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
            args:
              [
                "--joal-conf=/config",
                "--spring.main.web-environment=true",
                "--server.port=8090",
                "--joal.ui.path.prefix=nastiness",
                "--joal.ui.secret-token=${SECRET_JOAL_TOKEN}",
              ]
            resources:
              requests:
                memory: 420Mi
                cpu: 20m
              limits:
                memory: 510Mi
                cpu: 100m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 8*60=480 seconds to start up before it fails
                  periodSeconds: 8
                  failureThreshold: 60
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_JOAL_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8090
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "joal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "joal.${SECRET_DOMAIN}"
            secretName: joal-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
