# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: shopping-cards
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"${SECRET_GHCR_USERNAME}","password":"${SECRET_GHCR_PULL_TOKEN}"}}}'
