apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: obsidian-couchdb-configmap
    files:
      - config/config.ini
resources:
  - namespace.yaml
  - helm-release.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled