apiVersion: v1
kind: Secret
metadata:
    name: kured-secret
    namespace: kured
stringData:
    notifyUrl: ENC[AES256_GCM,data:aAzmSmiRF4+cCnIM8Kq1I+nwGy9TjeqgqKpPOiQ3UUvceTySlC4wweFHpsidw3oNo0puLIOicTU2L/8jFLkca5IRkVgyXY+6l3093eSOLNEVp2w=,iv:Uj0OuWA8BRNzOocKHQDN6pUNsYY7XT+qU0KVbDB+ELI=,tag:VpI2LCgVwHuWQsPouchFpA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T13:48:59Z"
    mac: ENC[AES256_GCM,data:eO2bwReoT4aXbPtqfLU1K4NoxpAxlqOI1iYW9P1JiMF52bljvByRH/Jgo/8azJo9Jx3vSrNkvvZCvRrJ5V9hyAGgAaDxqqQvJWVcTcSWocY19Ajbc4ADNoIgHY5dOzugHP8B5KWDYjqraikPpE9mUEjt1tibEh82G+KjULNyc8A=,iv:MqZhDpZLG4+wOhnNcnk8frTmLGd7jXlbmGiJ2WLisS0=,tag:IDVtSOnV7LbaztlQorB7hg==,type:str]
    pgp:
        - created_at: "2026-05-29T13:48:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4AQ//W7GRQGabhCtrqrHz+nkGt5R/y7yalcWU3GDtsl4frHfu
            BqfXM7Ou5o8JW4kGuRFxVnet8OpGinlBnEjA7vUh5v+7tgCLa23aPahZNT8Lf8Zw
            sfKiueAv+6sBohJCj6OQOtZ70wDvN+ru5put69uF3HhoFb4v6dSuPRgy+XuAGJft
            6UX5Hme63cLAN1fqk7C9tPeS+4lAQPiou8xky8uThXNPEXzdtGlNAzb0XKUd9lwJ
            AGPDcO69bXceLmSwg2lr/w0uj0RzlCSpFh7u7HfedM+MHVSzVwK6riL/hB4N+HPe
            PedA6Fw1UquT6kI78a/MtMMCS8p19VMIYV+dJvyEJ98NM9ZpEo6oPYSiCVPC0d2J
            lzM1SS8lx5hSWSAXU/Bx528EAeoL+katT9J0evd24itHsShQdB9p5uImeatLGkLx
            KyH3so0DanXesq0B8x5QwrW/x3p4MHAJMqORhJm/HNUSosPEfCeJqXAJSDRDJLOy
            o1RO3zjMKCpj7JKBmgLVyanX2LatAP2NNY7KD5soQnNeOFLVurOu0edrvTxeXJ37
            GVBbNoUAnRrRYcJgUZhZDpE6FIgvhMfERVJWyv/OjpBuoGxWHQWtnRvs3uqJAz4t
            inOIa4zJlgM3RqbXNgi4AEf3w8w18S3o5coBQ8szUlkYISEdkw0cMvbSBFnYoAvU
            ZgEJAhBQkY8Nsox8TKKLo8zKq0iHtoflY/HkoGWNxl6GdgDMDm/5QRZe7r1Vui5y
            6Sd/4Rt32oELRFiqWKn+UAZ2HAdozRJTxJKyMe58snG0yn8zTRbXy0rhbAg7XRLv
            10RxPZLu8A==
            =At4r
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-05-29T13:48:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2ARAA4R0fQdXcEiBIKS9OM8fk1t/phvYYgkZZ7+icuneEEy/x
            ZQ56ljyed9WXygeJBXq850uIcCGgnfnFNGOTe+CmQOCIZHsu6GL0PIHYBRh9pNkz
            TCcVyUEv4QrIsJ0uoP3mbs7MyCYMeZnmdxiR53X2Zgrg8U0ZxwelNbWmFLZM/UwL
            iDYiNLdkhfdTjfWEbjFACgZRuxYZb4hw40r85Gh8kg+8AiQQpg0YH+TiG9QBSyX4
            xStZ7GZALUlWDq2aKfE/PgEZAkNaxNa4bvrPwGvEr82VWlpIhhWgAjAiXaOuDdt4
            D/yNa0Pk+9WTQVn62ScDJdp2+Ph/INAMmjhuvK/kTU8iPCIc23MVIjwKPm+FEU6+
            iqQMjTtIp4oiPvXLLCtbAhMurT6psNlX+BorQQJgotJJXS7K2ZwP8FMo70zYl968
            2tfsLq+6mWJFl216zg9jnJgW2do8PY1lcBjBdzhKsYOTku/uipsTNzGia/n2I7HJ
            ZCxWLyxAME7Ez/ltj88yKpes3PaY6Pij6mobVJGLk6KNI+MmXuq2oOYg87oFacH+
            6XJ5ngnxwh7HvF8KXYhsFRyB6/UhtGNf5fv3SqKvWMVo7VKLplWFHK1uVPkf1Lrz
            466SasAvvqaVP30gC5L7FTrTjRz3ugAbV2EosQsXZEVAipbz0NMWpAr11BtH8xTU
            ZgEJAhCsMUpk2uyrTChgSRMxmy1+hXoSkJnL0kN4CqzlMiS0t2xeLgPmOtgTjBPC
            aE/C4tMFEqGDEO0qmic+/QcUVmVGsV9Kf3u9u1NnMlpR8T9gW3w5QNV1224YxWEq
            /g+VfthymA==
            =7NsQ
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    version: 3.13.1
