---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      enableServiceLinks: false
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/authelia/authelia
              tag: "4.39.15"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
            resources:
              requests:
                memory: 1024Mi
                cpu: 200m
              limits:
                memory: 1024Mi
                cpu: 500m
            probes:
              startup:
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 8*60=480 seconds to start up before it fails
                  periodSeconds: 8
                  failureThreshold: 60
    service:
      main:
        enabled: true
        externalTrafficPolicy: Local
        controller: main
        ports:
          http:
            enabled: true
            port: 9091
            protocol: HTTP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
            secretName: auth-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "2Gi"
      logs:
        enabled: true
        storageClass: "synology-iscsi-storage"
        accessMode: ReadWriteOnce
        size: "5Gi"
        advancedMounts:
          main:
            main:
              - path: /var/log/authelia
            