---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: transmission
  namespace: transmission
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: linuxserver/transmission
              tag: "2021.11.18"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                memory: 512Mi
                cpu: 500m
              limits:
                memory: 1024Mi
                cpu: 1500m
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
              pullPolicy: Always
            env:
              TZ: Europe/Paris
              VPN_SERVICE_PROVIDER: cyberghost
              OPENVPN_USER: ${SECRET_VPN_USERNAME}
              OPENVPN_PASSWORD: ${SECRET_VPN_PASSWORD}
              UPDATER_PERIOD: 24h
              SERVER_COUNTRIES: Belgium
              HEALTH_VPN_DURATION_INITIAL: 30s
              HEALTH_SUCCESS_WAIT_DURATION: 30s
            securityContext:
              privileged: true
              capabilities:
                add: ["NET_ADMIN"]
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_TRANSMISSION_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 9091
            protocol: HTTP
          torrent:
            enabled: false
            port: 51413
            protocol: TCP
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          main:
            main:
              - path: /config
      gluetun:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
        advancedMounts:
          main:
            gluetun:
              - path: /gluetun
      media:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media/download
        advancedMounts:
          main:
            main:
              - path: /data/download
