---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: transmission
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/transmission
              tag: "4.0.5"
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Paris
              PUID: 1000
              PGID: 1000
              USER: ${SECRET_TRANSMISSION_USER}
              PASS: ${SECRET_TRANSMISSION_PASSWORD}
            resources:
              requests:
                memory: 128Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 500m
    service:
      main:
        enabled: true
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${SVC_TRANSMISSION_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 9091
            protocol: HTTP
          torrent:
            enabled: true
            port: 51413
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "transmission.${SECRET_DOMAIN}"
            secretName: transmission-tls-secret
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        size: "1Gi"
      media:
        type: nfs
        server: 192.168.1.10
        path: /volume1/media
        globalMounts:
          - path: /data/torrent
