---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 1h0m0s
  timeout: 30m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: "v0.107.65"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    service:
      main:
        primary: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_ADGUARD_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "adguard-home"
        ports:
          http:
            enabled: true
            port: 80
            protocol: TCP
            targetPort: 3000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_ADGUARD_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "adguard-home"
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_ADGUARD_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: "adguard-home"
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    persistence:
      config:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /opt/adguardhome/conf
        size: "50Mi"
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /opt/adguardhome/work
        size: "2Gi"
    resources:
      requests:
        cpu: 25m
        memory: 60Mi
      limits:
        cpu: 50m
        memory: 75Mi
    config: |
      bind_host: 0.0.0.0
      bind_port: 3000
      beta_bind_port: 0
      users: []
      auth_attempts: 5
      block_auth_min: 15
      http_proxy: ""
      language: fr
      rlimit_nofile: 0
      debug_pprof: false
      web_session_ttl: 720
      dns:
        bind_hosts:
        - 0.0.0.0
        port: 53
        statistics_interval: 1
        querylog_enabled: true
        querylog_file_enabled: true
        querylog_interval: 90
        querylog_size_memory: 1000
        anonymize_client_ip: false
        protection_enabled: true
        blocking_mode: default
        blocking_ipv4: ""
        blocking_ipv6: ""
        blocked_response_ttl: 10
        parental_block_host: family-block.dns.adguard.com
        safebrowsing_block_host: standard-block.dns.adguard.com
        ratelimit: 0
        ratelimit_whitelist: []
        refuse_any: true
        upstream_dns:
        - https://dns10.quad9.net/dns-query
        upstream_dns_file: ""
        bootstrap_dns:
        - 9.9.9.10
        - 149.112.112.10
        - 2620:fe::10
        - 2620:fe::fe:10
        all_servers: false
        fastest_addr: false
        allowed_clients: []
        disallowed_clients: []
        blocked_hosts: []
        cache_size: 4194304
        cache_ttl_min: 0
        cache_ttl_max: 0
        bogus_nxdomain: []
        aaaa_disabled: false
        enable_dnssec: false
        edns_client_subnet: false
        max_goroutines: 300
        ipset: []
        filtering_enabled: true
        filters_update_interval: 24
        parental_enabled: false
        safesearch_enabled: false
        safebrowsing_enabled: false
        safebrowsing_cache_size: 1048576
        safesearch_cache_size: 1048576
        parental_cache_size: 1048576
        cache_time: 30
        rewrites: []
        blocked_services: []
        local_domain_name: lan
        resolve_clients: true
        local_ptr_upstreams: []
      tls:
        enabled: false
        server_name: ""
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 784
        port_dnscrypt: 0
        dnscrypt_config_file: ""
        allow_unencrypted_doh: false
        strict_sni_check: false
        certificate_chain: ""
        private_key: ""
        certificate_path: ""
        private_key_path: ""
      filters:
      - enabled: true
        url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: false
        url: https://adaway.org/hosts.txt
        name: AdAway
        id: 2
      - enabled: false
        url: https://www.malwaredomainlist.com/hostslist/hosts.txt
        name: MalwareDomainList.com Hosts List
        id: 4
      whitelist_filters: []
      user_rules: []
      dhcp:
        enabled: false
        interface_name: ""
        dhcpv4:
          gateway_ip: ""
          subnet_mask: ""
          range_start: ""
          range_end: ""
          lease_duration: 86400
          icmp_timeout_msec: 1000
          options: []
        dhcpv6:
          range_start: ""
          lease_duration: 86400
          ra_slaac_only: false
          ra_allow_slaac: false
      clients: []
      log_compress: false
      log_localtime: false
      log_max_backups: 0
      log_max_size: 100
      log_max_age: 3
      log_file: ""
      verbose: false
      schema_version: 10
