---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/seblaporte/home-assistant
      tag: '2024.5.5'
      pullPolicy: Always
    controller:
      type: deployment
      strategy: Recreate
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    service:
      main:
        primary: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_HOME_ASSISTANT_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 80
            protocol: TCP
            targetPort: 8123
    dnsPolicy: ClusterFirst
    hostNetwork: true
    termination:
      gracePeriodSeconds: 30
      messagePath: /dev/termination-log
      messagePolicy: File
    probes:
      startup:
        enabled: true
        spec:
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 100
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "home-assistant.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "home-assistant.${SECRET_DOMAIN}"
            secretName: home-assistant-tls-secret
    persistence:
      data:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /config
        size: "10Gi"
      camera-snapshots:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /camera-snapshots
        size: "1Gi"
      media:
        enabled: true
        storageClass: "nfs-client"
        accessMode: "ReadWriteOnce"
        mountPath: /media
        size: "10Gi"
    resources:
      requests:
        memory: 1400Mi
        cpu: 200m
      limits:
        memory: 1600Mi
        cpu: 500m
