apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kitchenvault-dev
resources:
  - ../base
  - namespace.yaml
  - secret.sops.yaml
patches:
  - path: patch-backend-ingress.yaml
  - path: patch-frontend-ingress.yaml
