---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kitchenvault-frontend
spec:
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: "2026.8.2-rc.2"
