---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kitchenvault-backend
spec:
  values:
    controllers:
      main:
        containers:
          main:
            env:
              KITCHENVAULT_CORS_ALLOWED_ORIGINS: "https://kitchenvault-dev.${SECRET_DOMAIN}"
