apiVersion: v1
kind: Secret
metadata:
    name: kitchenvault-secrets
    namespace: kitchenvault-dev
stringData:
    #ENC[AES256_GCM,data:MW6TyZZjjhpp4hK2pEkAcsIHYkw=,iv:9/3/HAPjxqyZE4/LiDSD3fuv0pGaIR3jkWdmp9SiYtI=,tag:pvbjQ1ckHU1mOXg0cYz8mg==,type:comment]
    postgres-user-password: ENC[AES256_GCM,data:ZLMGWRJNK7ElqQfjb4BX1tmOvJ3XUy9Ybi4lVE8na5xQQc885uDYHuMRvLF1YRGK,iv:UtvUZxJ+i03duOVafpkEAg6Vjr4u9IEzSeaq/KZ0i+g=,tag:pylKYfJDWAllv8p/CppsCg==,type:str]
    #ENC[AES256_GCM,data:QteRnfbIrL2355trCIEVq7LoGqa4,iv:vgQITfnpydyFgSBSo65rBeRJfxCEQyWUyxw8pgKRqcs=,tag:NgcEMFB0CW491DHIWpvbhg==,type:comment]
    COOKIDOO_EMAIL: ENC[AES256_GCM,data:dPUOCmB80BgyYIFnvCyenyvpTcnXGw==,iv:uxuhORMq3CYtrTHsGrpqWWpaDl923Cz63ZeJmOKbdBg=,tag:NhoO4Dj2YhzoiURR/e+QnQ==,type:str]
    COOKIDOO_PASSWORD: ENC[AES256_GCM,data:yid6gStx4ZfQWgBNYUSZvQ==,iv:h05LcJufAYOcmRpolb0vvxZ8vBtbl0aAZqeUEGcDlt4=,tag:D4ALstJdWSv0eTQMXzwD8w==,type:str]
sops:
    lastmodified: "2026-05-04T20:52:45Z"
    mac: ENC[AES256_GCM,data:6D8pQUtJjIGi5OFghxbhqm1cFtC/RERCvQOLw8HX89DHp+y377+H9VJcdQBEkEn2zeGcSK2Er/rNtLF6k6/X1zzgDPVc4InY4/kojMD7HwsnxTMlVWwb9jrOmDV76VZzkCCOs/bhiwV1Ip8hntJS910MrRkK4cRxwpHr2syWleY=,iv:5OPtsf1vn6aSTPjtx9c0XUVNOL0dOEbS8kZnr1wq+iI=,tag:5MrcMUYnqzJOnuTN78swnA==,type:str]
    pgp:
        - created_at: "2026-05-04T20:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XQQ6Mv5hr4ARAAqGwVNBQBVckiF+MATLtGsou4d49rK5z/EGZDx3JkK1oj
            VGbVh14R0xsYUD6DXL5FCXuyg8y++lDfoOOw1meOggRvM1YA26V0QNxXmce9St1+
            p1dPkjRmjH0dMrsFfwx3OmFRmwI7lVThozHz+TQ/a+W24QvW3BdQOgfCaej/yEx3
            G3OZzbnkianhK34ZLkjRa7ZuDZwLT1c7oPxy+WQAEAR5nhjnWLYhLGjOcoX12Zzy
            3xG+Gk002eS12ACAr9gjUlbVuBVVGA/YR81xlYQyrX0wesjjg+POJBiLDs+jnz6A
            ZAFFuX7DWkF2u1g2ItCN35JS9PdisZvSmoOHxj03F67FpiI5cX7gLzFpvzLJAVVl
            o6YlrXg1rg+CArWqGgFOcHdg53bQn2oOXog81efiHtwBFuT300lf6qjYSLpXmPX7
            a4EBbvif4fkwkDo7M+9TYbN4eIiAy+H4G9PnJc9Z4LsZ+03P0nMA8OXOoc4WOo4x
            miQnJ0WZPvliqXR/aG8NPy64vVRO7M56pbH3CYB6Uy4T+oWuekk0bzk0pmfYKNAx
            jpPX5dLmjoJzsQjl5sG/Xo3AOibcBjrHAHisci4EHXwLFCXTgYJc7iJ9V9xTf5Mg
            UhTfl2UKvTCmL3hR9ZdI18dv6Z18SvpzLbP11eI/ICEXFhQ7y2gYNbP/M6foVhnU
            aAEJAhDZn72yNTvp2uIBXj7oLhWAVGOMCSWl5WRenvWnVMlBz62iIY+E5G9SqK/S
            c4a4DtZtmavcO7o+fN8XRrnFDYOO3wi9KALNOfdz8JWbOZVToZI6UXUzghJil0A4
            pGYrNYFJSf8a
            =IYoF
            -----END PGP MESSAGE-----
          fp: 869E3023F74007F7821BB7ECEBAC2E3EFE9A20EE
        - created_at: "2026-05-04T20:52:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/69SZB81yo2AQ/9EBsJ4JO6t+anc7kvcd/trLT8r5DyscgIfZ1xlep02Ubp
            boJpmYPBa6TT6e9sj8Nin7rQhy/Nl7FuR/CWUyVJtNj19iKpyAlJ//Rcj9x1hJmK
            cOhKrIAEKoKwIf+8bW13TMF5t6p+4vjem7Euaty2vyhOSz6uko/1LkMvzgNBx4s0
            B+Cc4hQEn9Brot5VBkQfS2F5pRY3ke1JGI8i9bcyW4akk3mAJZIjS1PU8h6vm0Pk
            4sby1Xb8INOMgC2slpTe1dre8HrAB+xKsI7MJsB/QVrCByzaOSxHPaKD4sO3FMN5
            KCkC8bVedhLF+uLY/W7/XscyqvDEaASHzGqJCGT6rtMv87qt3iosfLa8ChdkKXao
            44misxavJkvbSeY2guoDxpSeNZl0XHrbUopwL4w4XNfco+NvKkaOcxinULkvtWRf
            aAv8Cm/jbXSOAkHsIxW2lT/byRseBkZLAMexuoDa7PNngLyZ+ZtbVbLiqf8j2jis
            OYmsNnkP2y5BaJ+bnjUxKMI8PWhDkUIFlR2ZdMqdOD5wtWks3HVRTx+yxDK01UOp
            9g7TRET4F3K0sfGMr8yMF24BiN6Erw45nIFbqv3+YyrXoxVnNlGu+F63dEjyhPtX
            x0FQvznyoNY8DROLXi2JktbFKinKy+v2b3cg5wOAYaJOnSGvRqG/6bw3CuyRQBjU
            aAEJAhDCfm96m9hHr7sfzfyDWR04y6xpVmoeS5Njoiy3lJf6ceUwyfk4ubD4yChp
            s4FhGEP+gZK1npQhhWzkA64Jbm6sABMeIjnn3e+baD6QbNoB/XIoo4YW5PgKfsOd
            iQd/EiLc7zPD
            =PFlx
            -----END PGP MESSAGE-----
          fp: 18EDD040B5E94B61B9B8AA8D7A09A4F01237221C
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
