---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arduino2mqtt
  namespace: arduino2mqtt
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      interval: 15m
  values:
    defaultPodOptions:
      nodeSelector:
        nodetype: hardware-gateway
      tolerations:
        - key: "hardware"
          operator: "Exists"
          effect: "NoSchedule"
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/seblaporte/arduino2mqtt
              tag: latest
              pullPolicy: Always
            resources:
              requests:
                memory: 25Mi
                cpu: 10m
              limits:
                memory: 35Mi
                cpu: 20m
            securityContext:
              # Privileged securityContext required by USB devices accessed directly through the host machine
              privileged: true
    persistence:
      arduino:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Uno_6493832333135180D1F0-if00
        globalMounts:
          - path: /dev/ttyACM1
    service:
      main:
        enabled: false